name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: ${{ secrets.SERVICE_NAME }}
  REGION: ${{ secrets.REGION }}
  IMAGE_URL: gcr.io/cabby-392012/cabby-service:latest

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Check Types
        run: npm run check:types

      - name: Prettier Check
        run: npm run format:check

      - name: Build
        run: npm run build

  deploy-staging:
    environment:
      name: staging
    if: github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize' || (github.event.action == 'closed' && !github.event.pull_request.merged))
    needs: build-and-check
    runs-on: ubuntu-latest
    steps:
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
          
      - name: Deploy to Cloud Run Staging
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: staging-${{ secrets.SERVICE }}
          region: ${{ secrets.REGION }}
          image: ${{ env.IMAGE_URL }}

  deploy-production:
    environment:
      name: production
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build-and-check
    runs-on: ubuntu-latest
    steps:
      - name: Google Auth
          id: auth
          uses: 'google-github-actions/auth@v0'
          with:
            credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
            
      - name: Deploy to Cloud Run Production
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: production-${{ secrets.SERVICE }}
          region: ${{ secrets.REGION }}
          image: ${{ env.IMAGE_URL }}
